### ISSUE TITLE
Syntax error within _print.scss 

### ISSUE THREAD

**Issue by melimind** [detfaellesdesignsystem/dkfds-components#57] opened 2019-08-29 08:44 UTC
I'm trying to use dkdfds within an Angular application.

I reference DKFDS within global styles.scss like so:

```
@import "~dkfds/src/stylesheets/dkfds-virkdk";
```

Application fails to publish due to following error within DKFDS package:

```
Failed to compile.

./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  &.table--responsive-headers:not(.d-print-table) {
 ^
      Top-level selectors may not contain the parent selector "&".
    ╷
119 │   &.table--responsive-headers:not(.d-print-table) {
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\dkfds\src\stylesheets\core\_print.scss 119:3  @import
  node_modules\dkfds\src\stylesheets\_dkfds-base.scss 59:9   @import
  node_modules\dkfds\src\stylesheets\dkfds-virkdk.scss 6:9   @import
  stdin 8:9                                                  root stylesheet
      in C:\Users\dev\development\nl3\nl-ui\node_modules\dkfds\src\stylesheets\core\_print.scss (line 119, column 3)
```

**Comment by detfaellesdesignsystem** [comment] 2019-08-29 12:32
Hej @melimind 

I have put it in the backlog and we will look at it as soon as possible. Thank you for sharing it with us.

Best regards 
Sune
Det Fælles Designsystem

**Comment by detfaellesdesignsystem** [comment] 2019-08-30 09:43
Hi @melimind

We've fixed the issue and it'll be in the next release.

I've been trying to reproduce the error you posted using a plain angular project, but I have not been able to get the errormessage you posted. Could you send us some more info on what you are doing to get this error? What kind of command? 

I would like to be able to test for this in the future.

Best regards
Kristina Jensen
Det Fælles Designsystem

**Comment by melimind** [comment] 2019-08-30 10:35
Hi Kristina,


Here are the steps for error reproduction:

Creating new project:

```
C:\Source
λ ng new xyz
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
...
```

Adding dependency:

```
C:\Source
λ cd xyz\

C:\Source\xyz (master -> origin)
λ npm add dkfds
```

Adding import `@import "~dkfds/src/stylesheets/dkfds-virkdk";` to styles.scss:

```
C:\Source\xyz (master -> origin)
λ vi src\styles.scss
```

Building:

```
C:\Source\xyz (master -> origin)
λ ng build

chunk {main} main-es2015.js, main-es2015.js.map (main) 48 kB [initial] [rendered]
chunk {polyfills} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 264 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5-es2015.js, polyfills-es5-es2015.js.map (polyfills-es5) 617 kB [initial] [rendered]
chunk {runtime} runtime-es2015.js, runtime-es2015.js.map (runtime) 6.16 kB [entry] [rendered]
chunk {styles} styles-es2015.js, styles-es2015.js.map (styles) 10.3 kB [initial] [rendered]
chunk {vendor} vendor-es2015.js, vendor-es2015.js.map (vendor) 3.75 MB [initial] [rendered]
Date: 2019-08-30T10:29:41.125Z - Hash: cc6760b1ea1fdcf39de6 - Time: 17183ms

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  &.table--responsive-headers:not(.d-print-table) {
 ^
      Top-level selectors may not contain the parent selector "&".
    ╷
119 │   &.table--responsive-headers:not(.d-print-table) {
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\dkfds\src\stylesheets\core\_print.scss 119:3  @import
  node_modules\dkfds\src\stylesheets\_dkfds-base.scss 59:9   @import
  node_modules\dkfds\src\stylesheets\dkfds-virkdk.scss 6:9   @import
  stdin 2:9                                                  root stylesheet
      in C:\Source\xyz\node_modules\dkfds\src\stylesheets\core\_print.scss (line 119, column 3)
```

:-)

Best regards

Mindaugas

**Comment by detfaellesdesignsystem** [comment] 2019-08-30 11:41
Hi @melimind 

Thanks for the very detailed description, it helped a lot. We do not use angular in DKFDS - only for testing purposes and my version was apparently old enough to not return that error. But now I'm getting it, and hopefully we'll be able to avoid these errors in the future.

I'm closing the issue here since it has been fixed now and will be available in the next release.

Best regards
Kristina Jensen
Det Fælles Designsystem

**Closed by detfaellesdesignsystem** 2019-08-30 11:41 UTC
